#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
  
{{- if .Values.gui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-cell-tracer-poc.fullname" . }}-gui-internal
  labels: {{- include "eric-oss-cell-tracer-poc.labels" . | nindent 4 }}
  annotations: {{- include "eric-oss-cell-tracer-poc.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ipFamilyPolicy: PreferDualStack
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  {{- end }}
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backend
    - name: frontend
      protocol: TCP
      port: 8090
      targetPort: frontend
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-cell-tracer-poc.name" . }}-gui
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.gui.exposed}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-cell-tracer-poc.fullname" . }}-gui
  labels: {{- include "eric-oss-cell-tracer-poc.labels" . | nindent 4 }}
    ui.ericsson.com/part-of: {{ .Values.gui.partOf | quote }}
  annotations: {{- include "eric-oss-cell-tracer-poc.annotations" . | nindent 4 }}
    ui.ericsson.com/port: '8090'
    ui.ericsson.com/protocol: http
    ui.ericsson.com/config-context: /{{- .Values.gui.contextPath }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
spec:
  type: {{ .Values.service.type | quote }}
  ipFamilyPolicy: PreferDualStack
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  {{- end }}
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backend
    - name: frontend
      protocol: TCP
      port: 8090
      targetPort: frontend
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-cell-tracer-poc.name" . }}-gui
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}