#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

#Metrics related configurations
management.endpoints.web.exposure.include: "*"
management.endpoint.info.enabled: "true"
management.endpoint.metrics.enabled: "true"
management.endpoint.prometheus.enabled: "true"
management.prometheus.metrics.export.enabled: "true"
management.info.env.enabled: "true"

management.endpoint.health.probes.enabled: "true"
management.health.liveness-state.enabled: "true"
management.endpoint.health.group.liveness.exclude: readinessState
management.health.readiness-state.enabled: "true"
management.endpoint.health.group.readiness.exclude: livenessState


#opentracing.jaeger.enabled: "true"
spring:
  profiles:
    active: "production"
  jackson:
    default-property-inclusion: "non_null"
  flyway:
    enabled: true
  datasource:
    hikari:
      maxLifetime: 600000
    url: ${DB_URL:jdbc:postgresql://eric-oss-cell-tracer-poc-database-pg:5432/eric-oss-cell-tracer-poc}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
  kafka:
    properties:
      sasl.mechanism: OAUTHBEARER
      security.protocol: PLAINTEXT
      sasl.login.callback.handler.class: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      oauth.ssl.truststore.location: ${TRUST_STORE_LOCATION:}/truststore.jks
      oauth.ssl.truststore.password: ${TRUST_STORE_PASSWORD:}
      ssl.truststore.location: ${TRUST_STORE_LOCATION:}/truststore.jks
      ssl.truststore.password: ${TRUST_STORE_PASSWORD:}
    schema-registry.url: ${SCHEMA_REGISTRY:http://eric-schema-registry-sr:8081}
  security.oauth2.client:
    registration.eic:
      authorization-grant-type: client_credentials
      client-id: ${CLIENT_ID:}
      client-secret: ${CLIENT_SECRET:}
    provider.eic.token-uri: ${BASE_URL:http://localhost}/auth/realms/${TENANT:master}/protocol/openid-connect/token
#============================================================================
# Quartz scheduler
#============================================================================
  quartz:
    job-store-type: jdbc
    jdbc.initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true
    properties.org.quartz:
      scheduler:
        instanceId: AUTO
      jobStore:
        class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        misfireThreshold: 60000
        clusterCheckinInterval: 10000
        isClustered: true

rapp-sdk:
  bdr:
    enabled: false
  kafka:
    oauth: false
    group-prefix: cell-tracer-rapp
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVICE:eric-oss-dmm-kf-op-sz-kafka-bootstrap:9092}
    enabled: true
    autoStart: true
    consumers:
      nrevents:
        group-id: nrevents
        topics: 5g-pm-event-file-transfer-and-processing--enm1
        listener-class: NREventDataRetrieval
    sender:
      events:
        nrtopic: 5g-pm-event-file-transfer-and-processing--enm1
  ncmp:
    enabled: true
    base-path: ${BASE_URL:http://localhost}/ncmp
  dcc:
    enabled: ${DCC_ENABLED:true}
    base-path: ${BASE_URL:http://localhost}/dmm-data-collection-controller
  catalog:
    enabled: false

app:
  data:
    config: ${APP_DATA_CONFIG:classpath:}
    customerid: ${CUSTOMER_ID:netsim}
    events:
      maxEventsReturned: 1000
  generator:
    events:
      enabled: ${EVENT_GENERATOR_ENABLED:false}
      rate: ${EVENT_GENERATOR_RATE:-}
  security:
    certificates: ${CA_CERT_LOCATION:}
  scheduling:
    enabled: true
  asn1:
    decoder:
      enabled: false
      max-retries: 4
      backoff:
        delay: 100
        multiplier: 2

grpc:
  client:
    asn1Decoder:
      address: ${ASN1_DECODER_URL:static://localhost:8082}
      keep-alive-without-calls: true
      enable-keep-alive: true
      negotiationType: plaintext

cm-extract:
  batchSize: 20
  refreshRate: 3600000

pm:
  ropTimeExpirePeriod: 8
  cleaningScheduler: 0 */15 * * * *

endpoints.health.sensitive: "false"
info.app.name: '@name@'
info.app.description: Microservice chassis app
info.app.version: '@version@'
info.app.legal: "COPYRIGHT Ericsson 2021 -
 The copyright to the computer program(s) herein is the property of
 Ericsson Inc. The programs may be used and/or copied only with written
 permission from Ericsson Inc. or in accordance with the terms and
 conditions stipulated in the agreement/contract under which the
 program(s) have been supplied."

#See more details about pattern layout: https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html
#See more details about logging.pattern.level : https://docs.spring.io/spring-boot/docs/2.5.2/reference/html/features.html#features.logging.custom-log-configuration
#logging.pattern.level: "%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}][%X{userName}]"

#Set the stubrunner credentials:
#stubrunner.username: <LAN SIGNUM ID>
#stubrunner.password: <LAN encripted PWD or JFrog API Key>
stubrunner.username: ${SELI_ARTIFACTORY_REPO_USER}
stubrunner.password: ${SELI_ARTIFACTORY_REPO_PASS}
